# Experiment
log_dir: vit_pet
overwrite: true

# Model
model_name: base
patch_size: 16
image_dim: [3, 224, 224]
components: []

# Data
dataset_name: pet
batch_size: 512
val_batch_size: 512

# Training
n_steps: 4_000
train_size: 0.8
grad_acc_steps: 1
grad_clip: 1

# Optimizer
optimizer: sgd
lr: 1e-2
momentum: 0.9

# Scheduler
scheduler: "cosine"

# Evaluation
eval_period: 200

# Device
device: cuda:0

# Orchestrator
logging_period: 40
logging_level: INFO
seed: 42
utility_period:  1000